
# Environment variable names
YEAR_ENV_VARIABLE = 'YEAR'
PATH_ENV_VARIABLE = 'SOURCE_PATH'
FOLDER_ENV_VARIABLE = 'SOURCE_FOLDER'
EXPENSES_ENV_VARIABLE = 'EXPENSES_FILENAME'
SUMMARY_BY_MONTH_ENV_VARIABLE = 'SUMMARY_BY_MONTH'
SUMMARY_BY_TYPE_ENV_VARIABLE = 'SUMMARY_BY_TYPE'

# Input data columns' names
MONTH_COL = 'month'
MONTH_NUMBER_COL = 'month_number'
DATE_COL = 'date'
TRANSACTION_COL = 'transaction'
TRANSACTION_TYPE_COL = 'type'
